insta485/views/admin.py
"""
Insta485 admin view.

URLs include:
/accounts/login/
/accounts/logout/
/accounts/create/
/accounts/edit/
/accounts/delete/
/accounts/password/
"""

from flask import Blueprint, render_template, redirect, url_for, session,\
    Response
from insta485 import model
from insta485.views.db_scripts import GET_USER_FULL_INFO


admin = Blueprint("admin", __name__)


@admin.route("/login/")
def login():
    """Display /accounts/login/ route."""
    return render_template("login.html") if "logname" not in session else\
        redirect(url_for('misc.home'))


@admin.route("/logout/", methods=["POST"])
def logout() -> Response:
    """Display /accounts/logout/ route."""
    session.clear()
    return redirect(url_for('admin.login'))


@admin.route("/create/")
def create():
    """Display /accounts/create/ route."""
    return render_template("create.html") if "logname" not in session else\
        redirect(url_for('admin.edit'))


@admin.route("/delete/")
def delete():
    """Display /accounts/delete/ route."""
    return redirect(url_for('admin.login')) if "logname" not in session else\
        render_template("delete.html", logname=session["logname"])


@admin.route("/edit/")
def edit():
    """Display /accounts/edit/ route.

    context = {"fullname": , "email": , "filename": , "logname": }
    """
    if "logname" not in session:
        return redirect(url_for('admin.login'))
    context: dict = model.get_db().cursor().execute(
        GET_USER_FULL_INFO, (session["logname"],)).fetchone()
    context["logname"] = context.pop("username")
    return render_template("edit.html", **context)


@admin.route("/password/")
def password():
    """Display /accounts/password/ route."""
    return redirect(url_for('admin.login')) if "logname" not in session else\
        render_template("password.html", logname=session["logname"])

insta485/views/misc.py
"""
Insta485 misc view.

Renaming columns for sqlite3 ALTER TABLE ? RENAME COLUMN old_col TO new_col;
URLs include:
/
/explore/
/posts/
"""
from sqlite3 import Cursor
from flask import Blueprint, render_template, send_from_directory, redirect,\
    url_for, session, abort
from arrow import utcnow, get
from insta485 import app, model
from insta485.views.users import fol_exp
from insta485.views.db_scripts import GET_HOME_POSTS_ALL_INFO,\
    GET_USER_FULL_INFO, GET_LIKER, GET_COMMENT_INFO_PER_POST, GET_EXPLORE,\
    GET_POST_FULL_INFO


misc = Blueprint("misc", __name__)


@misc.route('/')
def home():
    """Display / route.

    context = {"logname":, "posts": [{post1}, {post2}]}
    each_post = {
        "postid": ,
        "filename"(post-content): ,
        "owner": ,
        "created":  ,
        "pfp": ,
        "likes"(#likes): ,
        "liked"(logname liked?): ,
        "comments": [{"owner": , "text":, "commentid"}, {}]
    }
    """
    if "logname" not in session:
        return redirect(url_for('admin.login'))
    logname: str = session["logname"]
    context: dict = {"logname": logname}
    cursor: Cursor = model.get_db().cursor()
    context["posts"] = cursor.execute(
        GET_HOME_POSTS_ALL_INFO, (logname, logname)).fetchall()
    for post in context["posts"]:
        post["created"] = get(post["created"]).humanize(utcnow())
        post["pfp"] = cursor.execute(
            GET_USER_FULL_INFO, (post["owner"],)).fetchone()["filename"]
        users_liked = cursor.execute(
            GET_LIKER, (post["postid"],)).fetchall()
        post["likes"] = len(users_liked)
        post["liked"] = {"owner": logname} in users_liked
        post["comments"] = cursor.execute(
            GET_COMMENT_INFO_PER_POST, (post["postid"],)).fetchall()
    return render_template("index.html", **context)


@misc.route("/explore/")
def explore():
    """Display /explore/ route."""
    return redirect(url_for('admin.login')) if "logname" not in session else\
        fol_exp("", True, "explore", GET_EXPLORE)


@misc.route("/posts/<postid>/")
def posts(postid: int):
    """Display /posts/<postid>/ route.

    context = {
        "logname": ,
        "postid": ,
        "post":{"postid": , "filename"(pic): , "owner": , "created": , "pfp":,
        "num_likes": , "liked": , "comments": ["owner":,"text":,"commentid":]}
    }
    """
    if "logname" not in session:
        return redirect(url_for('admin.login'))
    logname: str = session["logname"]
    context: dict = {"logname": logname, "postid": postid}
    cursor: Cursor = model.get_db().cursor()
    context["post"] = cursor.execute(
        GET_POST_FULL_INFO, (postid,)).fetchone()
    context["post"]["created"] = get(
        context["post"]["created"]).humanize(utcnow())
    context["post"]["pfp"] = cursor.execute(
        GET_USER_FULL_INFO, (context["post"]["owner"],)).fetchone()["filename"]
    users_liked = cursor.execute(GET_LIKER, (postid, )).fetchall()
    context["post"]["num_likes"] = len(users_liked)
    context["post"]["liked"] = {"owner": logname} in users_liked
    context["post"]["comments"] = cursor.execute(
        GET_COMMENT_INFO_PER_POST, (postid,)).fetchall()
    return render_template("post.html", **context)


@misc.route('/uploads/<filename>')
def render_pic(filename: str):
    """Render picture from /var/uploads/<filename>/ route."""
    if "logname" not in session:
        abort(403)
    if not (app.config["UPLOAD_FOLDER"]/filename).exists():
        abort(404)
    return send_from_directory(app.config['UPLOAD_FOLDER'], filename)

insta485/views/users.py
"""
Insta485 users view.

URLs include:
/users/<username>/
/users/<username>/following/
/users/<username>/followers/
"""
from sqlite3 import Cursor
from flask import Blueprint, render_template, redirect, url_for, session,\
    abort
from insta485 import model
from insta485.views.db_scripts import GET_USER_FULL_INFO, GET_FOLLOWERS,\
    GET_FOLLOWING, GET_PROFILE_POSTS_INFO


users = Blueprint("users", __name__)


@users.route("/<username>/")
def user_profile(username: str):
    """Display /users/<username>/ route.

    context = {
        "logname": ,
        "username": ,
        "range"(func): ,
        "fullname": ,
        "num_followers": ,
        "num_following": ,
        "logname_fol_user"(T/F): ,
        "num_posts": ,
        "posts": [{"postid": , "filename": }, {}]
    }
    """
    if "logname" not in session:
        return redirect(url_for('admin.login'))
    cursor: Cursor = model.get_db().cursor()
    if cursor.execute(GET_USER_FULL_INFO, (username,)).fetchone() is None:
        abort(404)
    logname: str = session["logname"]
    context: dict = {"logname": logname,
                     "username": username, "range": range}
    cursor.execute(GET_USER_FULL_INFO, (username,))
    context["fullname"] = cursor.fetchone()["fullname"]
    cursor.execute(GET_FOLLOWERS, (username, ))
    follower_list: list[dict] = cursor.fetchall()
    context["num_followers"] = len(follower_list)
    cursor.execute(GET_FOLLOWING, (username, ))
    context["num_following"] = len(cursor.fetchall())
    cursor.execute(GET_FOLLOWING, (logname, ))
    context["logname_fol_user"] = {
        "username2": username} in cursor.fetchall()
    cursor.execute(GET_PROFILE_POSTS_INFO, (username,))
    posts: list[dict] = cursor.fetchall()
    context["num_posts"] = len(posts)
    context["posts"] = posts
    return render_template("user.html", **context)


def fol_exp(username: str, explore: bool, template: str, dbscript: str):
    """For following, followers, and explore.

    context = {
        "logname": ,
        "accounts": [{"acc_name": , "pfp": , "logname_fol_acc"}, {}],
        "explore": False
    }
    """
    cursor: Cursor = model.get_db().cursor()
    if not explore and cursor.execute(
            GET_USER_FULL_INFO, (username,)).fetchone() is None:
        abort(404)
    logname: str = session["logname"]
    context: dict = {"logname": logname, "accounts": [], "explore": explore}
    placeholder: set = (username,) if not explore else (logname, logname)
    cursor.execute(dbscript, placeholder)
    for i in cursor.fetchall():
        account: dict = {"acc_name": i["username" if explore else (
            "username1" if dbscript == GET_FOLLOWERS else "username2")]}
        cursor.execute(GET_USER_FULL_INFO, (account["acc_name"],))
        account["pfp"] = cursor.fetchone()["filename"]
        if not explore:
            cursor.execute(GET_FOLLOWERS, (account["acc_name"],))
            account["logname_fol_acc"] = {
                "username1": logname} in cursor.fetchall()
        context["accounts"].append(account)
    return render_template(f"{template}.html", **context)


@users.route("/<username>/followers/")
def user_followers(username: str):
    """Display /users/<username>/followers/ route."""
    return redirect(url_for('admin.login')) if "logname" not in session else\
        fol_exp(username, False, "followers", GET_FOLLOWERS)


@users.route("/<username>/following/")
def user_following(username: str):
    """Display /users/<username>/following/ route."""
    return redirect(url_for('admin.login')) if "logname" not in session else\
        fol_exp(username, False, "following", GET_FOLLOWING)

insta485/templates/create.html
{%- extends "navbar_base.html" %}
{%- block content %}
<div id="main-container">
    <div id="forms" class="create">
        <div id="labels">
            <div class="row"><label for="photo">Photo</label><br></div>
            <div class="row"><label for="name">Name</label><br></div>
            <div class="row"><label for="username">Username</label><br></div>
            <div class="row"><label for="email">Email</label><br></div>
            <div class="row"><label for="password">Password</label><br></div>
        </div>
        <form action="{{ url_for('postonly.accounts', target=url_for('misc.home')) }}" method="POST" enctype="multipart/form-data" id="CEP">
            <input id="photo" type="file" name="file" required/><br>
            <input id="name" type="text" name="fullname" required/><br>
            <input id="username" type="text" name="username" required/><br>
            <input id="email" type="text" name="email" required/><br>
            <input id="password" type="password" name="password" required/><br>
            <input class="pec" type="submit" name="signup" value="sign up"/>
            <input type="hidden" name="operation" value="create"/>
        </form>
    </div>
    <div id="bottom-link">Have an account? <a href="{{ url_for('admin.login') }}">Log in</a></div>
</div>
{%- endblock content %}

insta485/templates/delete.html
{%- extends "navbar_base.html" %}
{%- block content %}
<div class="delete-container">
    <p>{{ logname }}</p>
    <form action="{{ url_for('postonly.accounts', target=url_for('admin.create')) }}" method="POST" enctype="multipart/form-data">
        <input type="submit" name="delete" value="confirm delete account"/>
        <input type="hidden" name="operation" value="delete"/>
    </form>
</div>
{%- endblock content %}

insta485/templates/edit.html
{%- extends "navbar_base.html" %}
{%- block content %}
<div id="main-container">
    <div id="lil-profile">
        <div id="pfp"><img src="{{ url_for('misc.render_pic', filename=filename) }}" alt="{{logname}}'s pfp"></div>
        <div id="username">{{ logname }}</div>
    </div>
    <div id="forms" class="edit">
        <div id="labels">
            <div class="row"><label for="photo">Photo</label><br></div>
            <div class="row"><label for="name">Name</label><br></div>
            <div class="row"><label for="email">Email</label><br></div>
        </div>
        <form action="{{ url_for('postonly.accounts', target=request.url) }}" method="POST" enctype="multipart/form-data" id="CEP">
            <input id="photo" type="file" name="file" accept="image/*"/><br>
            <input id="name" type="text" name="fullname" value="{{ fullname }}" required/><br>
            <input id="email" type="text" name="email" value="{{ email }}" required/><br>
            <input class="pec" type="submit" name="update" value="submit"/>
            <input type="hidden" name="operation" value="edit_account"/>
        </form>
    </div>
    <div class="redirect"><a href="{{ url_for('admin.password') }}">Change password</a></div>
    <div class="redirect"><a href="{{ url_for('admin.delete') }}">Delete account</a></div>
</div>
{%- endblock content %}

insta485/templates/explore.html
{%- extends "folexp_base.html" %}
{%- block FE_header %}Discover People{% endblock FE_header %}

insta485/templates/folexp_base.html
{%- extends "navbar_base.html" %}
{%- block content %}
<div class="big-header">{% block FE_header %}{% endblock FE_header %}</div>
{%- for account in accounts %}
<div class="base-container">
    <div class="account">
        <div class="pfp"><img src="{{ url_for('misc.render_pic', filename=account.pfp) }}" alt="{{ account.acc_name }}'s pfp"></div>
        <div class="username"><a href="{{ url_for('users.user_profile', username=account.acc_name) }}">{{ account.acc_name }}</a></div>
    </div>
    <div class="display">
        {%- if not explore and logname != account.acc_name %}
        <div class="follow-text">{%- if account.logname_fol_acc %}following{%- else %}not following{%- endif %}</div>
        {%- endif %}
        {%- if logname != account.acc_name %}
        <form action="{{ url_for('postonly.following', target=request.url) }}" method="POST" enctype="multipart/form-data" class="follow-button">
            <input type="submit" name="{%- if account.logname_fol_acc %}unfollow{%- else %}follow{%- endif %}" value="{%- if account.logname_fol_acc %}unfollow{%- else %}follow{%- endif %}"/>
            <input type="hidden" name="username" value="{{ account.acc_name }}"/>
            <input type="hidden" name="operation" value="{%- if account.logname_fol_acc %}unfollow{%- else %}follow{%- endif %}"/>
        </form>
        {%- endif %}
    </div>
</div>
{%- endfor %}
{%- endblock content %}

insta485/templates/followers.html
{%- extends "folexp_base.html" %}
{%- block FE_header %}Followers{% endblock FE_header %}

insta485/templates/following.html
{%- extends "folexp_base.html" %}
{%- block FE_header %}Following{% endblock FE_header %}

insta485/templates/index.html
{%- extends "navbar_base.html" %}
{%- block content %}
    <div id="reactEntry">Loading ...</div>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bundle.js') }}"></script>
{%- endblock content %}

insta485/templates/index_old.html
{%- extends "navbar_base.html" %}
{%- block content %}
    {%- for post in posts %}
    <div class="post index">
        <div class="header">
            <div class="post-er">
                <div class="pfp"><a href="{{ url_for('users.user_profile', username=post.owner) }}"><img src="{{ url_for('misc.render_pic', filename=post.pfp) }}" alt="{{ post.owner }}'s pfp"></a></div>
                <div class="username"><a href="{{ url_for('users.user_profile', username=post.owner) }}">{{ post.owner }}</a></div>
            </div>
            <div class="time-posted"><a href="{{ url_for('misc.posts', postid=post.postid) }}">{{ post.created }}</a></div>
        </div>
        <div class="content">
            <div class="pic"><img src="{{ url_for('misc.render_pic', filename=post.filename) }}" alt="{{ post.owner }}'s {{ post.created }} post"></div>
            <div class="remaining">
                <div class="like">
                    {%- if post.likes == 1 %} {{ post.likes }} like
                    {%- else %} {{ post.likes }} likes
                    {%- endif %}
                </div>
                <div class="comments">
                    {%- for comment in post.comments %}
                    <p><a href="{{ url_for('users.user_profile', username=comment.owner) }}">{{ comment.owner }}</a> {{ comment.text }}</p>
                    {%- endfor %}
                </div>
            </div>
        </div>
        <div class="new-buttons index">
            <form action="{{ url_for('postonly.likes', target=request.url) }}" method="POST" enctype="multipart/form-data" class="likeunlike">
                <input type="hidden" name="operation" value="{%- if post.liked %}unlike{%- else %}like{%- endif %}"/>
                <input type="hidden" name="postid" value="{{ post.postid }}"/>
                <input type="submit" name="{%- if post.liked %}unlike{%- else %}like{%- endif %}" value="{%- if post.liked %}unlike{%- else %}like{%- endif %}"/>
            </form>
            <form action="{{ url_for('postonly.comments', target=request.url) }}" method="POST" enctype="multipart/form-data">
                <input type="hidden" name="operation" value="create"/>
                <input type="hidden" name="postid" value="{{ post.postid }}"/>
                <input type="text" name="text" required/>
                <input type="submit" name="comment" value="comment"/>
            </form>
        </div>
    </div>
    {%- endfor %}
{%- endblock content %}

insta485/templates/login.html
{%- extends "navbar_base.html" %}
{%- block content %}
<div id="main-container">
    <form action="{{ url_for('postonly.accounts', target=url_for('misc.home')) }}" method="POST" enctype="multipart/form-data" class="login">
        <input type="text" name="username" placeholder="username" required/><br>
        <input type="password" name="password" placeholder="password" required/><br>
        <input type="submit" value="login"/>
        <input type="hidden" name="operation" value="login"/>
    </form>
    <div id="bottom-link">Don't have an account? <a href="{{ url_for('admin.create') }}">Sign up</a></div>
</div>
{%- endblock content %}

insta485/templates/navbar_base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
        <title>insta485</title>
    </head>
    <body>
        <header>
            <div class="left-header">
                <div class="home"><a href="{{ url_for('misc.home') }}"><img src="{{ url_for('static', filename='/images/logo.png') }}" alt="Instagram logo"></a></div>
                <div class="insta">Insta485</div>
            </div>
            <div class="right-header">
                <div class="right-header-container">
                    {%- if logname %}
                    <div class="explore"><a href="{{ url_for('misc.explore') }}">explore</a></div>
                    <div class="logname"><a href="{{ url_for('users.user_profile', username=logname) }}">{{ logname }}</a></div>
                    {%- else %}
                    <div class="login-navbar">login</a></div>
                    {%- endif %}
                </div>
            </div>
        </header>
        <hr>
        {%- block content %}{%- endblock %}
    </body>
</html>

insta485/templates/password.html
{%- extends "navbar_base.html" %}
{%- block content %}
<div id="main-container">
    <div id="forms" class="password">
        <div id="labels">
            <div class="row"><label for="pw">Old password</label><br></div>
            <div class="row"><label for="pw1">New password</label><br></div>
            <div class="row"><label for="pw2">New password, again</label><br></div>
        </div>
        <form action="{{ url_for('postonly.accounts', target=url_for('admin.edit')) }}" method="POST" enctype="multipart/form-data" id="CEP">
            <input id="pw" type="password" name="password" required/><br>
            <input id="pw1" type="password" name="new_password1" required/><br>
            <input id="pw2" type="password" name="new_password2" required/><br>
            <input class="pec" type="submit" name="update_password" value="submit"/>
            <input type="hidden" name="operation" value="update_password"/>
        </form>
    </div>
    <div class="redirect"><a href="{{ url_for('admin.edit') }}">Back to edit account</a></div>
</div>
{%- endblock content %}

insta485/templates/post.html
{%- extends "navbar_base.html" %}
{%- block content %}
<div class="post-container">
    <div class="pic"><img src="{{ url_for('misc.render_pic', filename=post.filename) }}" alt="{{ post.owner }}'s {{ post.created }} post"></div>
    <div class="remaining">
        <div class="header">
            <div class="post-er">
                <div class="pfp"><a href="{{ url_for('users.user_profile', username=post.owner) }}"><img src="{{ url_for('misc.render_pic', filename=post.pfp) }}" alt="{{ post.owner }}'s pfp"></a></div>
                <div class="username"><a href="{{ url_for('users.user_profile', username=post.owner) }}">{{ post.owner }}</a></div>
            </div>
            <div class="time-posted"><a href="{{request.url}}">{{ post.created }}</a></div>
        </div>
        <div class="comments">
            <div class="like">{%- if post.num_likes == 1 %}{{ post.num_likes }} like{%- else %}{{ post.num_likes }} likes{%- endif %}</div>
            {%- for comment in post.comments %}
            <div class="comment-wrapper">
                <p><a href="{{ url_for('users.user_profile', username=comment.owner) }}">{{ comment.owner }}</a> {{ comment.text }}</p>
                {%- if logname == comment.owner %}
                <form action="{{ url_for('postonly.comments', target=request.url) }}" method="POST" enctype="multipart/form-data">
                    <input type="hidden" name="operation" value="delete"/>
                    <input type="hidden" name="commentid" value="{{ comment.commentid }}"/>
                    <input type="submit" name="uncomment" value="delete"/>
                </form>
                {%- endif %}
            </div>
            {%- endfor %}
            <form action="{{ url_for('postonly.likes', target=request.url) }}" method="POST" enctype="multipart/form-data" class="likeunlike">
                <input type="hidden" name="operation" value="{%- if post.liked %}unlike{%- else %}like{%- endif %}"/>
                <input type="hidden" name="postid" value="{{ post.postid }}"/>
                <input type="submit" name="{%- if post.liked %}unlike{%- else %}like{%- endif %}" value="{%- if post.liked %}unlike{%- else %}like{%- endif %}"/>
            </form>
            <form action="{{ url_for('postonly.comments', target=request.url) }}" method="POST" enctype="multipart/form-data">
                <input type="hidden" name="operation" value="create"/>
                <input type="hidden" name="postid" value="{{ post.postid }}"/>
                <input type="text" name="text" required/>
                <input type="submit" name="comment" value="comment"/>
            </form>
            {%- if logname == post.owner %}
            <div class="del-post">
                <form action="{{ url_for('postonly.posts', target=url_for('users.user_profile', username=logname)) }}" method="POST" enctype="multipart/form-data">
                    <input type="hidden" name="operation" value="delete"/>
                    <input type="hidden" name="postid" value="{{ post.postid }}"/>
                    <input type="submit" name="delete" value="delete this post"/>
                </form>
            </div>
            {%- endif %}
        </div>
    </div>
</div>
{%- endblock content %}

insta485/templates/user.html
{%- extends "navbar_base.html" %}
{%- block content %}
<div class="profile">
    <div class="personal-info">
        <div class="acc-name">{{ username }}</div>
        {%- if logname == username %}
        <div class="edit-profile"><a href="{{ url_for('admin.edit') }}">Edit profile</a></div>
        <form action="{{ url_for('admin.logout') }}" method="POST" enctype="multipart/form-data" class="logout-button">
            <input type="submit" name="logout" value="Logout"/>
        </form>
        {%- else %}
        <div class="relationship">
            <div class="follow-text">
                {%- if logname_fol_user %}following
                {%- else %}not following
                {%- endif %}
            </div>
            <form action="{{ url_for('postonly.following', target=request.url) }}" method="POST" enctype="multipart/form-data" class="follow-button">
                <input type="submit" name="{%- if logname_fol_user %}unfollow{%- else %}follow{%- endif %}" value="{%- if logname_fol_user %}unfollow{%- else %}follow{%- endif %}"/>
                <input type="hidden" name="username" value="{{ username }}"/>
                <input type="hidden" name="operation" value="{%- if logname_fol_user %}unfollow{%- else %}follow{%- endif %}"/>
            </form>
        </div>
        {%- endif %}
        <div class="info">
            {%- if num_posts == 1 %}{{ num_posts }} post
            {%- else %}{{ num_posts }} posts
            {%- endif %}
            <a href="{{ url_for('users.user_followers', username=username) }}">
                {%- if num_followers == 1 %}{{ num_followers }} follower
                {%- else %}{{ num_followers }} followers
                {%- endif %}
            </a>
            <a href="{{ url_for('users.user_following', username=username) }}">{{ num_following }} following</a>
        </div>
        <div class="fullname">{{ fullname }} </div>
    </div>
    {%- if logname == username %}
    <form action="{{ url_for('postonly.posts', target=request.url) }}" method="POST" enctype="multipart/form-data" class="upload">
        <input type="file" name="file" accept="image/*" required/>
        <input type="submit" name="create_post" value="upload new post"/>
        <input type="hidden" name="operation" value="create"/>
    </form>
    {%- endif %}
    {%- if num_posts != 0 %}
    <div class="post user">
        {%- for idx in range((num_posts + 1) // 2) %}
        <div class="row-container">
            <div><a href="{{ url_for('misc.posts', postid=posts[idx * 2].postid) }}"><img src="{{ url_for('misc.render_pic', filename=posts[idx * 2].filename) }}" alt="post {{ posts[idx * 2].postid }}"></a></div>
            {%- if idx * 2 + 1 != num_posts %}
            <div><a href="{{ url_for('misc.posts', postid=posts[idx * 2 + 1].postid) }}"><img src="{{ url_for('misc.render_pic', filename=posts[idx * 2 + 1].filename) }}" alt="post {{ posts[idx * 2 + 1].postid }}"></a></div>
            {%- endif %}
        </div>
        {%- endfor %}
    </div>
    {%- endif %}
</div>
{%- endblock content %}